version: 2
updates:
  # JavaScript/Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/agent-dashboard"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "security-team"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jsonwebtoken"
        update-types: ["version-update:semver-major"]
    groups:
      # Group all non-security updates
      development-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
      production-dependencies:
        patterns:
          - "*"
        dependency-type: "production"
        exclude-patterns:
          - "express"
          - "jsonwebtoken"
          - "bcrypt"

  # Client dependencies
  - package-ecosystem: "npm"
    directory: "/agent-dashboard/client"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

# Security updates have precedence
# Dependabot will open PRs for security updates as soon as they're available
# regardless of the schedule